Refactor wrapped_set_value for clarity and structure
fixed error:- 
### App Versions
```
{
	"appraisal_salary": "0.0.1",
	"b2b_marketing": "0.0.1",
	"biometric_integration_ftp": "0.0.1",
	"clefincode_chat": "1.3.2",
	"drive": "0.3.0",
	"erpnext": "15.94.0",
	"esign_app": "0.0.1",
	"follow_up": "0.0.1",
	"frappe": "15.95.0",
	"frappe_whatsapp": "1.0.7",
	"helpdesk": "1.18.1",
	"hrms": "15.54.2",
	"india_compliance": "15.24.2",
	"lending": "0.0.1",
	"lms": "2.44.0",
	"mint": "1.1.2",
	"new_dex_web": "0.0.1",
	"next_ai": "0.0.1",
	"next_crm": "2.0.0-dev",
	"nextarrear": "0.0.1",
	"nextnotify": "0.0.1",
	"nextproject": "15.0.1",
	"opportunity_temperature": "0.0.1",
	"payments": "0.0.1",
	"printformat": "0.0.1",
	"quickdo": "1.1.0",
	"raven": "2.6.6",
	"telephony": "0.0.1",
	"ticketing": "0.0.1",
	"timeclock": "0.0.1"
}
```
### Route
```
Form/HD Ticket/new-hd-ticket-aynuwqwres
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 120, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 52, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 40, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 53, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1754, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 378, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 400, in _save
    return self.insert()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 326, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 1011, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1371, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1353, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1008, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py", line 181, in after_insert
    self.create_communication_via_contact(self.description, new_ticket=True)
  File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py", line 685, in create_communication_via_contact
    c.save(ignore_permissions=True)
  File "apps/frappe/frappe/model/document.py", line 378, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 400, in _save
    return self.insert()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 326, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 1011, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1371, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1355, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/crm/utils.py", line 92, in update_modified_timestamp
    frappe.db.set_value(
TypeError: _patch_db_set_value_for_value_change.<locals>.wrapped_set_value() missing 2 required positional arguments: 'doctype' and 'name'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"HD Ticket\",\"name\":\"new-hd-ticket-axakttzikd\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"psharma@dexciss.io\",\"custom_module\":\"\",\"custom_helpdesk_task_information\":[],\"sla\":\"Default\",\"agreement_status\":\"\",\"opening_date\":\"2026-01-12\",\"via_customer_portal\":0,\"is_merged\":0,\"custom_merged_hd_tickets\":[],\"__run_link_triggers\":false,\"customer\":\"The Udemba Group\",\"subject\":\"TUG Website Updates\",\"ticket_type\":\"Technical Bug\",\"description\":\"<div class=\\\"ql-editor read-mode\\\"><p>Page to be listed on menu item.</p></div>\",\"custom_contact_email\":\"suraj@dexciss.io\",\"contact\":\"Suraj\",\"project\":\"PROJ-IN-25-05-127\",\"creation\":\"\",\"modified_by\":\"psharma@dexciss.io\",\"modified\":\"\",\"lft\":null,\"rgt\":null,\"__newname\":\"new-hd-ticket-ceulvwpovv\",\"idx\":null,\"on_paste_event\":true}",
		"action": "Save"
	},
	"btn": {
		"jQuery3700486271222610962451": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1470,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "TypeError: _patch_db_set_value_for_value_change.<locals>.wrapped_set_value() missing 2 required positional arguments: 'doctype' and 'name'",
	"exc_type": "TypeError",
	"_exc_source": "helpdesk (app)"
}
```